"use strict";
const clone=x=>JSON.parse(JSON.stringify(x));
function integer(x,l,h,name){if(!Number.isInteger(x)||x<l||x>h)throw new RangeError(name);return x;}
function gcd(a,b){while(b){const t=a%b;a=b;b=t;}return a;}
function pc(x){let n=0;for(;x;x&=x-1)n++;return n;}
function construct(base,sidon,input){
 if(input.schema!=="commons.ordered_cap3_input/v1"||input.N!==19||input.score_start!==4||input.score_end!==19||base.N!==19||base.g!==2||base.nodes.length!==6423||sidon.base_node_count!==6423)throw new TypeError("bound inputs required");
 const N=19,full=(1<<N)-1,nodes=base.nodes.map(clone),work={saved_nodes:nodes.length,saved_witnesses:sidon.witnesses.length,witness_filters:0,selected_witnesses:0,new_pair_sums:0,new_support_unions:0,old_constraint_constructions:0,old_coefficient_recomputations:0,refinement_states:0,memo_hits:0,skipped_drops:0,unchanged_returns:0,old_node_reuses:0,new_unique_hits:0,zero_high_reductions:0,new_nodes:0,new_coefficient_cells:0,family_path_visits:0,family_rows:0,prefix_cells:0,score_comparisons:0};
 for(let i=0;i<nodes.length;i++){const z=nodes[i];if(z.id!==i||!Array.isArray(z.coefficients))throw new TypeError("node identity");if(i>1&&(!Number.isInteger(z.v)||z.v<0||z.v>=19||z.lo<0||z.hi<0||z.lo>=i||z.hi>=i||nodes[z.lo].v<=z.v||nodes[z.hi].v<=z.v))throw new TypeError("node order");}
 const witnesses=[];for(const w of sidon.witnesses){work.witness_filters++;if(w.pairs.length!==2)throw new TypeError("witness pair count");if(w.pairs.every(p=>p[0]<p[1]))witnesses.push(clone(w));}
 const constraints=[...new Set(witnesses.map(w=>w.mask))].sort((a,b)=>a-b);work.selected_witnesses=witnesses.length;
 const unique=new Map(nodes.slice(2).map(z=>[[z.v,z.lo,z.hi].join(","),z.id])),memo=new Map();
 function mk(v,lo,hi){if(hi===0){work.zero_high_reductions++;return lo;}const key=[v,lo,hi].join(",");if(unique.has(key)){const old=unique.get(key);work[old<base.nodes.length?"old_node_reuses":"new_unique_hits"]++;return old;}const a=nodes[lo].coefficients,b=nodes[hi].coefficients,c=Array(Math.max(a.length,b.length+1)).fill(0n);for(let i=0;i<a.length;i++)c[i]+=BigInt(a[i]);for(let i=0;i<b.length;i++)c[i+1]+=BigInt(b[i]);while(c.length&&c.at(-1)===0n)c.pop();work.new_coefficient_cells+=c.length;if(work.new_coefficient_cells>1000000)throw new RangeError("coefficient cap");const id=nodes.length;nodes.push({id,v,lo,hi,coefficients:c.map(String)});unique.set(key,id);work.new_nodes++;return id;}
 function refine(id,rs){if(id===0||id===1)return id;const z=nodes[id],before=(1<<z.v)-1,keep=[];for(const m of rs){if(m&before)work.skipped_drops++;else keep.push(m);}if(!keep.length){work.unchanged_returns++;return id;}const key=id+":"+keep.join(",");if(memo.has(key)){work.memo_hits++;return memo.get(key);}if(++work.refinement_states>200000)throw new RangeError("state cap");const bit=1<<z.v,lo=refine(z.lo,keep.filter(m=>!(m&bit)));let bad=false;const hr=[];for(const m of keep){const q=m&~bit;if(q===0){bad=true;break;}hr.push(q);}const hi=bad?0:refine(z.hi,[...new Set(hr)].sort((a,b)=>a-b));const out=mk(z.v,lo,hi);memo.set(key,out);return out;}
 const root=refine(base.root,constraints),rows=[],scoreGroups=new Map();
 function walk(id,mask){work.family_path_visits++;if(id===0)return;if(id===1){if(rows.length>=100000)throw new RangeError("row cap");let count=0,prefix="",bestNum=null,bestDen=1,ties=0;for(let n=1;n<=N;n++){if(mask&(1<<(n-1)))count++;prefix+=count.toString(36);work.prefix_cells++;if(n>=input.score_start){const a=count*count;work.score_comparisons++;const cmp=bestNum===null?-1:a*bestDen-bestNum*n;if(cmp<0){bestNum=a;bestDen=n;ties=1<<(n-input.score_start);}else if(cmp===0)ties|=1<<(n-input.score_start);}}const g=gcd(bestNum,bestDen),num=bestNum/g,den=bestDen/g,scoreKey=num+"/"+den;rows.push([mask,count,prefix,num,den,ties]);scoreGroups.set(scoreKey,(scoreGroups.get(scoreKey)||0)+1);work.family_rows++;return;}const z=nodes[id];walk(z.lo,mask);walk(z.hi,mask|(1<<z.v));}
 walk(root,0);
 const inheritedCount=nodes[root].coefficients.reduce((a,b)=>a+BigInt(b),0n);if(inheritedCount!==BigInt(rows.length))throw new Error("new family traversal count mismatch");
 const groups=[...scoreGroups].map(([key,count])=>{const[num,den]=key.split("/").map(Number);return{num,den,count};}).sort((a,b)=>a.num*b.den-b.num*a.den);
 return{schema:"commons.ordered_cap3_catalogue/v1",N,score_start:input.score_start,score_end:N,order:"decision bits 1..19, exclude before include; global row ID is array index",row_columns:["mask","size","base36_prefix_counts_1_to_19","score_numerator","score_denominator","score_minimizer_N_bitmask_from_4"],base:clone(input.base),sidon_source:clone(input.sidon),selected_witnesses:witnesses,constraints,base_node_count:base.nodes.length,delta_nodes:nodes.slice(base.nodes.length),root,coefficients:clone(nodes[root].coefficients),rows,score_groups:groups,summary:{total:rows.length,maximum_size:nodes[root].coefficients.length-1,maximum_size_count:nodes[root].coefficients.at(-1),maximum_score:clone(groups.at(-1)),inherited_B2_two_total:base.total},work};
}
function open(cert){
 if(cert.schema!=="commons.ordered_cap3_catalogue/v1"||cert.N!==19)throw new TypeError("catalogue");const full=(1<<19)-1,index=new Map(cert.rows.map((r,i)=>[r[0],i])),cache=new Map(),work={conditions:0,cache_hits:0,row_checks:0,quota_checks:0,rational_comparisons:0,selects:0,ranks:0,witness_checks:0,new_refinement:0,new_pair_sums:0,new_prefix_cells:0,new_score_calculations:0};
 function mask(values){if(!Array.isArray(values))throw new TypeError("values array");let m=0;for(const x of values){integer(x,1,19,"value");const b=1<<(x-1);if(m&b)throw new TypeError("duplicate value");m|=b;}return m;}
 function fraction(x){if(x===undefined)return null;if(!x||!/^\d+$/.test(String(x.num))||!/^\d+$/.test(String(x.den))||BigInt(x.den)===0n)throw new TypeError("nonnegative rational");return{num:String(BigInt(x.num)),den:String(BigInt(x.den))};}
 function normalize(raw={}){const required=mask(raw.required||[]),forbidden=mask(raw.forbidden||[]),quotas=Array(19).fill(0);for(const q of raw.prefix_min||[]){integer(q.N,1,19,"prefix N");integer(q.count,0,19,"prefix count");quotas[q.N-1]=Math.max(quotas[q.N-1],q.count);}const min_size=raw.min_size??0,max_size=raw.max_size??19;if(!Number.isInteger(min_size)||!Number.isInteger(max_size))throw new TypeError("integer size bounds");return{required,forbidden,quotas,min_size,max_size,score_min:fraction(raw.score_min),score_max:fraction(raw.score_max)};}
 function cmp(row,f){work.rational_comparisons++;const x=BigInt(row[3])*BigInt(f.den)-BigInt(f.num)*BigInt(row[4]);return x<0n?-1:x>0n?1:0;}
 function condition(raw={}){const c=normalize(raw),key=JSON.stringify(c);if(cache.has(key)){work.cache_hits++;return cache.get(key);}if(cache.size>=64)throw new RangeError("condition cache");const ids=[],sizeCounts=Array(20).fill(0);let best=null,bestIds=[];for(let i=0;i<cert.rows.length;i++){work.row_checks++;const r=cert.rows[i];if((r[0]&c.required)!==c.required||(r[0]&c.forbidden)||r[1]<c.min_size||r[1]>c.max_size)continue;let ok=true;for(let n=0;n<19;n++)if(c.quotas[n]){work.quota_checks++;if(parseInt(r[2][n],36)<c.quotas[n]){ok=false;break;}}if(!ok||c.score_min&&cmp(r,c.score_min)<0||c.score_max&&cmp(r,c.score_max)>0)continue;ids.push(i);sizeCounts[r[1]]++;const d=best===null?1:r[3]*best.den-best.num*r[4];if(d>0){best={num:r[3],den:r[4]};bestIds=[i];}else if(d===0)bestIds.push(i);}const out={key,condition:c,count:ids.length,ids,size_counts:sizeCounts,maximum_score:best,maximum_score_ids:bestIds};cache.set(key,out);work.conditions++;return out;}
 function row(id){integer(id,0,cert.rows.length-1,"row id");const r=cert.rows[id];return{row_id:id,mask:r[0],values:Array.from({length:19},(_,i)=>i+1).filter(x=>r[0]&(1<<(x-1))),size:r[1],prefix_counts:[...r[2]].map(x=>parseInt(x,36)),score:{num:r[3],den:r[4]},minimizer_N:Array.from({length:16},(_,i)=>i+4).filter(n=>r[5]&(1<<(n-4)))};}
 function selected(raw,rank,optimum=false){const q=condition(raw),ids=optimum?q.maximum_score_ids:q.ids;integer(rank,0,ids.length-1,"rank");work.selects++;return{rank,...row(ids[rank])};}
 function rank(raw,values,optimum=false){const m=mask(values),id=index.get(m),q=condition(raw),ids=optimum?q.maximum_score_ids:q.ids;work.ranks++;if(id===undefined)return{mask:m,row_id:null,rank:null};let lo=0,hi=ids.length;while(lo<hi){const mid=(lo+hi)>>1;if(ids[mid]<id)lo=mid+1;else hi=mid;}return{mask:m,row_id:id,rank:ids[lo]===id?lo:null};}
 function page(raw,start,limit=64,optimum=false){const q=condition(raw),ids=optimum?q.maximum_score_ids:q.ids;integer(start,0,ids.length,"start");integer(limit,0,256,"limit");const stop=Math.min(start+limit,ids.length);return{start,total:ids.length,next:stop<ids.length?stop:null,rows:ids.slice(start,stop).map((id,j)=>({rank:start+j,...row(id)}))};}
 return{summary:()=>clone(cert.summary),condition:raw=>clone(condition(raw)),row,select:(c,r)=>selected(c,r),rank:(c,v)=>rank(c,v),page:(c,s,l)=>page(c,s,l),optimumSelect:(c,r)=>selected(c,r,true),optimumRank:(c,v)=>rank(c,v,true),optimumPage:(c,s,l)=>page(c,s,l,true),explain:values=>{const m=mask(values),id=index.get(m);if(id!==undefined)return{member:true,...row(id)};for(const w of cert.selected_witnesses){work.witness_checks++;if((m&w.mask)===w.mask)return{member:false,witness:clone(w),ordered_lower_bound:4};}throw new Error("saved family completeness premise violated");},scoreGroups:()=>clone(cert.score_groups),work:()=>clone(work),snapshot:()=>({conditions:[...cache.values()].map(clone),work:clone(work)})};
}
module.exports={construct,open};
